-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = false,
            passes = 5,
        },
        inactive_opacity = 0.8,
        rounding = 5,
        rounding_power = 2.0,
        shadow = {
            enabled = false,
        },
    },
    general = {
        border_size = 2,
        gaps_in = 6,
        gaps_out = 6,
    },
    input = {
        accel_profile = "",
        natural_scroll = true,
        sensitivity = 0.1,
        touchpad = {
            clickfinger_behavior = true,
            disable_while_typing = false,
        },
    },
    misc = {
        animate_mouse_windowdragging = true,
    },
})

-- Keybinds
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.exec_cmd("kate"))
hl.unbind("SUPER + SHIFT + V")
hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("exec ~/.config/ml4w/scripts/ml4w-cliphist"))
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("vesktop"))
